### PR TITLE
MRG: fixes for Sphinx 7

### PR DESCRIPTION
**Pull request by matthew-brett**
Add fixes for compatibility with Sphinx >= 7.

### CODE REVIEW

**Comment by matthew-brett** [comment]
This one's ready to merge - any takers for a review?

**Comment by kloczek** [comment]
ItWorks ™️ https://github.com/matthew-brett/nb2plots/issues/28 😄

**Review by jarrodmillman — APPROVED** [review]
LGTM!

**Comment by matthew-brett** [comment]
OK - LGTM2 - merging, thanks.

**Pull request merged**
