### PR TITLE
Optionally render code output for nbplot directives

### PR DESCRIPTION
**Pull request by renefritze**
This is controlled via the `nbplot_render_output` setting, which
defaults to `False`, thereby keeping previous behaviour.

I was also thinking of replacing the current `exec` mechanism with something that behaves more like the default repl shell, like printing the repr of single only-expression lines.  

If this feature is of interest to you I could use some pointers how to properly write a test for this.

### CODE REVIEW

**Comment by matthew-brett** [comment]
Hi,

Please forgive my laziness - but could you give an idea of what that means
in terms of the rendered output - maybe with an example page before and
after?

Cheers,

Matthew

**Comment by renefritze** [comment]
Sure thing.  Given this rest snippet
```
.. nbplot::

    >>> a = 7
    >>> a

.. nbplot::

    >>> print(a)
```

the sphinx generated html previously showed basically this:
```
>>> a = 6
>>> a

>>> print(a)
```

With the change, and the option enabled, it now shows:
```
>>> a = 6
>>> a

>>> print(a)
6
```

And I would like to further tweak that to make it:
```
>>> a = 6
>>> a
6

>>> print(a)
6
```

That make sense?

**Comment by matthew-brett** [comment]
Yes, that makes sense.  It seems like a good idea, an option.  Is that
what you mean?

**Comment by renefritze** [comment]
Yeah. Not really sure what the sphinx terminology for settings in `conf.py` is but that is how I made it here. 
Could also be an argument to the `nbplots` directive itself, but in our project we would be using this for all directives anyway, so a global setting would be a good fit for us.

**Comment by renefritze** [comment]
I've updated the pythons checked on travis to include 3.8 since there's a breaking API change in the `ast.Module` code I use.

Getting my wanted printing behaviour to work was a little more involved and I had to look to IPython how to do it properly. 

Other than tests, I think I'm happy now. Does this still look OK for you @matthew-brett ?

**Comment by renefritze** [comment]
Sorry, @matthew-brett, I've since moved on from using nb2plots and would close this PR now. I'd be happy if you still want to use any of the changes, but I cannot put additional work in.

**Pull request closed without merging**
